version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - hipicasolera_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - ILICEReverseProxy

  hipicasolera:
    depends_on:
      - db
    image: wordpress:latest
    container_name: hipicasolera
    restart: always
    expose:
      - '80'
    volumes:
      - hipicasolera_wp_folder:/var/www/html
      - ./.htaccess:/var/www/html/.htaccess
    environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - ILICEReverseProxy

volumes:
   hipicasolera_db_data:
   hipicasolera_wp_folder:

networks:
  ILICEReverseProxy:
    external: true
